language: php
php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
env:
    matrix:
        - COVERAGE='--coverage-clover build/logs/clover.xml'
        - FUNC_TEST=components
        - FUNC_TEST=models
        - FUNC_TEST=controllers
        - FUNC_TEST=permissionsTests
        - FUNC_TEST=pageCrawlersAsAdminUser
        - FUNC_TEST=pageCrawlersAsGuest
        - FUNC_TEST=pageCrawlersAsTestUser
        - FUNC_TEST=pageCrawlersWithInjections
        - FUNC_TEST=webTrackingTests

services:
  - mysql

# blacklist
branches:
  except:
    - DemoServer
    - TrialServer

# For functional tests: webTrackingTests
addons:
  hosts:
    - www.x2enginetestdomain.com
    - www2.x2enginetestdomain.com
    - www.x2enginetestdomain2.com

before_script:
  - sudo apt-get update
  # xvfb is used for functional tests
  - sudo apt-get install -y apache2 libapache2-mod-fastcgi xvfb chromium-browser

  # start xvfb for functional tests
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  # pretend chromium is chrome
  - sudo ln -s /usr/bin/chromium-browser /usr/local/bin/google-chrome

  # install phpunit and associated packages
  - cd x2engine/protected/tests
  - composer global require phpunit/phpunit '4.8.0'
  - composer global require phpunit/phpunit-selenium '~1.2'
  - composer global require phpunit/phpunit-story
  - composer global require phpunit/dbunit '~1.2'
  - composer global require phpunit/php-invoker
  - export PATH=~/.composer/vendor/bin:$PATH
  - cd ../../..

  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf 2>/dev/null || true
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  # configure php ini file
  - echo 'date.timezone = "America/Los_Angeles"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'allow_url_fopen = on' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  # configure apache virtual hosts
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - sudo service apache2 restart

  # prep for coverage output
  - composer require satooshi/php-coveralls '~1.0'
  - mkdir -p build/logs

  # create mysql database and prevent 'mysql has gone away' during functional tests
  - mysql -e "DROP DATABASE IF EXISTS x2engine; CREATE DATABASE x2engine;" -u root;
  - mysql -e "SET GLOBAL max_allowed_packet = 1073741824;" -u root;
  - mysql -e "SET GLOBAL connect_timeout = 10800;" -u root;
  - mysql -e "SET GLOBAL wait_timeout = 10800;" -u root;
  - mysql -e "SHOW VARIABLES LIKE 'max_allowed_packet';" -u root;
  - mysql -e "SHOW VARIABLES LIKE 'connect_timeout';" -u root;
  - mysql -e "SHOW VARIABLES LIKE 'wait_timeout';" -u root;

  # install and run selenium in the background, wait to ensure selenium is running
  - wget http://selenium-release.storage.googleapis.com/2.48/selenium-server-standalone-2.48.2.jar -O /tmp/selenium-server-standalone-2.48.2.jar
  - DISPLAY=:99.0 java -jar /tmp/selenium-server-standalone-2.48.2.jar -browserSessionReuse -log /tmp/selenium.log &
  - sleep 10 

  # install x2crm
  - cp build/constants.php x2engine/constants.php
  - cp build/installConfig.php x2engine/installConfig.php
  - cd x2engine && php initialize.php silent && cd ..

  # configure tests
  - cp build/WebTestConfig.php x2engine/protected/tests/WebTestConfig.php

  # move functional test config closer to tests
  - cp build/phpunit_functional.xml x2engine/protected/tests/phpunit_functional.xml

# run tests
script: 
  # unit tests
  - if [[ -v COVERAGE ]]; then phpunit --configuration build/phpunit_unit.xml $COVERAGE x2engine/protected/tests/unit; fi

  # functional tests
  - if [[ -v FUNC_TEST ]]; then chmod +x build/functional_tests.sh; echo "Running functional tests..."; ./build/functional_tests.sh; fi

after_failure:
  # capture apache error log
  - sudo cat /var/log/apache2/error.log
  - sudo cat /var/log/mysql/error.log
  - sudo cat /tmp/selenium.log

after_success:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.3" ]]; then php vendor/bin/coveralls -v; fi
  - if [[ -v FUNC_TEST ]]; then sudo cat /tmp/report-$FUNC_TEST; fi

notifications:
  slack:
      secure: ieB8oa5aV1vIY1cQdk/eBHoFqOOrXfbjPs5YzstWoAC5WS3WO619ObpNjTiaZL/9/Ygr/b53eJ7ntAf6BRwwpbdJsxzk9HQy6/oHtvJxRwCJcmR3D64CAnKdeAQr64ohAXkNEHHVS8prFXy07tICntErvs00B9hnM9hjID0fOM6RbKP9Vqnw3Y7icC1JWgNOsxGrXB7AGA2smQNtEiiQmBNkg2RjpqtjaNdQXMk0/tzjEfwakn4SlwkKt6aRxJSWH+ezvP+5erFLqOFb5bSvjZcodDTWdOZVBS9NvUMusdvXItxo09Ynbv1qKUn1VzJG15bw2Id7pAtVwUg4hiT/0W8E8AoXfBO9Ag44r9SqQpelT33GzodgNjHx+N/jO/7nTlldZQ+P4KO/KavJcx/kfGVC+H2C1vjiAR1z4VHQdkifTjJUKdsm6MePRbACT8n69eW/05TYvQfKwkRcDsOVvntvrsyn+dKQWUnUWAYp+GaTLcfxsawF+uypltQ4aXDwAVdCLksTGBy+LLzYMCHRJRIFjHmgOSQ96Qs1iTMP0QYGQM3dJE6uGAJI8/rUlI1v+5cD+GdzABXjt0zulPLeCh8q2ROHVYWvMXmwXN1Xw+BjMQeeISTko9XiM2tWNU6JBFXFPNaxbIf0F4xfrS3dXkqpsXIj4pJacGNZghHsX4Y=

